# Base image
FROM wordpress:latest

# Remove the Apache web server
RUN rm /etc/apache2/conf-enabled/*

# Install Nginx and other dependencies
RUN apt-get update && apt-get install -y nginx \
    && rm -rf /var/lib/apt/lists/*

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Set file permissions
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Expose port 80 (default HTTP port)
EXPOSE 80

# Define the entrypoint script
ENTRYPOINT ["docker-entrypoint.sh"]

# Start Nginx and PHP-FPM
CMD ["nginx", "-g", "daemon off;"]
