---
- name: Deploy MySQL database
  hosts: database
  become: yes

  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
    - name: Create MySQL database
      mysql_db:
        name: my_database
        state: present

    - name: Create MySQL user
      mysql_user:
        name: my_user
        password: my_password
        priv: '*.*:ALL'
        host: localhost
        state: present