---
- name: Deploy MySQL database
  hosts: database
  become: yes

  tasks:
    - name: Check if MySQL is installed
      stat:
        path: /usr/bin/mysql
      register: mysql_installed

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
      when: mysql_installed.stat.exists == false
      
    - name: Create MySQL database
      mysql_db:
        name: test
        state: present

    - name: Create MySQL user
      mysql_user:
        name: test
        password: test
        priv: '*.*:ALL'
        host: localhost
        state: present