# ansible-playbook -i inventory.ini patch_windows_servers.yml --log-path=<path to file>

---
- name: Patch Windows servers
  hosts: windows_servers
  gather_facts: false
  serial: 1
  
  tasks:
 
    - name: Ping Windows Server
      win_ping:

    - name: Install Windows security updates
      win_updates:
        category_names: 
            - SecurityUpdates
            - CriticalUpdates
        state: installed
        reboot: true
        log_path: C:\ansible_patch.log
      register: update_result

    - name: Wait for server to come back online
      wait_for_connection:
        timeout: 300
        delay: 10
        
